### PR TITLE
call afterFirstLayout only if state is mounted

### PR DESCRIPTION
**Pull request by lukepighetti**

### CODE REVIEW

**Comment by marcglasberg** [comment]
I can confirm this solves the problem.

**Comment by marcglasberg** [comment]
Solves https://github.com/fluttercommunity/flutter_after_layout/issues/17

**Comment by alr2413** [comment]
is there any problem with this PR?

**Comment by chuiizeet** [comment]
i can confirm this pr works.

**Comment by slightfoot** [comment]
Thanks @lukepighetti  released as of v1.1.1 and you can use v1.2.0 with Flutter v3.0.0.

**Pull request merged**
